# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ebcf5d92169114c558c2ffe978407e9cc3d96412344c351fd97f7204ad509885e67ee01dc67e6dee53a965877cbd075f5dd3e9c798f602935980c85394477eb

test:
  secret_key_base: 39ec3154da4e08c8b2fdcc905cddda4d3a03869e706554ad4cbe4ff89fbd5e5fcad26fa8b89392f2026c01b627151f17ade6906ab3b1b30f8bcd204644aaebdd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
